ichiro-its/keisan

- .github/workflows/build-and-test.yml
- README.md
> Add build and test workflow

- CMakeLists.txt
- include/keisan/keisan.hpp
- include/keisan/point_2.hpp
- include/keisan/point_3.hpp
- src/point_2.cpp
- src/point_3.cpp
> Add Point Struct

- CMakeLists.txt
- include/keisan/angle.hpp
- include/keisan/keisan.hpp
- include/keisan/number.hpp
- src/angle.cpp
- src/number.cpp
- test/angle_test.cpp
- test/number_test.cpp
> 3 add angle equations

- CMakeLists.txt
- src/point_2.cpp
- src/point_3.cpp
- test/point_2_test.cpp
- test/point_3_test.cpp
> Add Test for Points

- include/keisan/number.hpp
- src/angle.cpp
- src/number.cpp
- test/number_test.cpp
> Add a Scale Number function

- README.md
- include/keisan/point_2.hpp
- include/keisan/point_3.hpp
- src/point_2.cpp
- src/point_3.cpp
- test/point_2_test.cpp
- test/point_3_test.cpp
> Add Distance Equation in Point Structs

- include/keisan/angle.hpp
- src/angle.cpp
- test/angle_test.cpp
> Add Delta Angle Equation

- include/keisan/number.hpp
- src/number.cpp
- test/number_test.cpp
> Add support to clamp number

- README.md
- include/keisan/point_2.hpp
- include/keisan/point_3.hpp
- src/angle.cpp
- src/point_2.cpp
- src/point_3.cpp
- test/point_2_test.cpp
- test/point_3_test.cpp
> Add Direction Equation

- include/keisan/point_2.hpp
- include/keisan/point_3.hpp
- src/point_2.cpp
- src/point_3.cpp
- test/point_2_test.cpp
- test/point_3_test.cpp
> Add Supoort for Dot Product and Cross Product

- CMakeLists.txt
- LICENSE
- README.md
- include/keisan/angle.hpp
- include/keisan/keisan.hpp
- include/keisan/number.hpp
- include/keisan/point_2.hpp
- include/keisan/point_3.hpp
- package.xml
- src/angle.cpp
- src/number.cpp
- src/point_2.cpp
- src/point_3.cpp
- test/angle_test.cpp
- test/number_test.cpp
- test/point_2_test.cpp
- test/point_3_test.cpp
> 21 wrong result in point2 direction

- CMakeLists.txt
- include/keisan/angle.hpp
- include/keisan/transform2.hpp
- src/angle.cpp
- src/transform2.cpp
- test/transform2_test.cpp
> Add Transform Class

- include/keisan/number.hpp
- src/number.cpp
> add number sign func

- include/keisan/point_2.hpp
- src/point_2.cpp
- src/transform2.cpp
- test/transform2_test.cpp
> Use Matrix For Transformation

- .gitignore
Add files to be ignored in the `.gitignore`.
> feat: ignore files from deb build

- .github/workflows/build-and-test.yml
- .github/workflows/deploy-debian-nightly.yml
- .github/workflows/deploy-debian-stable.yml
- .gitignore
- README.md
- package.xml
- Modify `build-and-test` workflow to use [ROS 2 build and test workspace](https://github.com/ichiro-its/ros2-build-and-test-action) action.
- Add `deploy-debian-nightly` and `deploy-debian-stable` workflows.
- Update information in the `README.md`.
> Modify workflows

- .github/workflows/deploy-documentation.yml
- .gitignore
- Doxyfile
- README.md
- Add a [Doxygen](https://www.doxygen.nl/) configuration.
- Add a `deploy-documentation` workflow.
> Add documentation

- CMakeLists.txt
- include/keisan/geometry/point_2.hpp
- include/keisan/geometry/point_3.hpp
- include/keisan/matrix/matrix.hpp
- include/keisan/matrix/square_matrix.hpp
- include/keisan/matrix/vector.hpp
- package.xml
- src/angle/angle.cpp
- src/geometry/point_2.cpp
- src/geometry/point_3.cpp
- test/geometry/point_2_test.cpp
- test/geometry/point_3_test.cpp
- test/matrix/matrix_test.cpp
- test/matrix/square_matrix_test.cpp
- test/matrix/vector_test.cpp
> Modify point equations

- CMakeLists.txt
- include/keisan/angle.hpp
- include/keisan/angle/angle.hpp
- include/keisan/angle/euler_angles.hpp
- include/keisan/angle/quaternion.hpp
- src/angle/angle.cpp
- src/angle/euler_angles.cpp
- src/angle/quaternion.cpp
- test/angle/angle_test.cpp
- test/angle/euler_angles_test.cpp
- test/angle/quaternion_test.cpp
Add a quaternion and an euler angles objects.
> Add quaternion

- .github/workflows/build-and-test.yml
- .github/workflows/deploy-debian-nightly.yml
- .github/workflows/deploy-debian-stable.yml
- test/angle/euler_test.cpp
- test/angle/quaternion_test.cpp
- test/matrix/matrix_inverse_test.cpp
https://ichiro-its.atlassian.net/browse/PD-373
Fix failed build in keisan unit tests at
- euler_test
- quaternion_test
- matrix_inverse_test
Update workflow (ubuntu & ros version)
- `feature/JIRA-ID-SHORT-DESCRIPTION` if has a JIRA ticket
- `enhancement/SHORT-DESCRIPTION` if has/has no JIRA ticket and contain enhancement
- `hotfix/SHORT-DESCRIPTION` if the change doesn't need to be tested (urgent)
> [Sprint 22 / PD-373] - [Hotfix] Fix Keisan Unit Tests

- CMakeLists.txt
- include/keisan/interpolation.hpp
- include/keisan/interpolation/polynom.hpp
- include/keisan/interpolation/polynom.impl.hpp
- include/keisan/interpolation/spline.hpp
- include/keisan/interpolation/spline.impl.hpp
- src/interpolation/polynom.cpp
- src/interpolation/spline.cpp
Added spline interpolation implementation in keisan, i. e. natural cubic, quadratic, and linear. Of course, added polynomial implementation as well.
- `feature/JIRA-ID-SHORT-DESCRIPTION` if has a JIRA ticket
- `enhancement/SHORT-DESCRIPTION` if has/has no JIRA ticket and contain enhancement
- `hotfix/SHORT-DESCRIPTION` if the change doesn't need to be tested (urgent)
> [Feature] - Implement Spline Interpolation

- CMakeLists.txt
- include/keisan/kalman.hpp
- include/keisan/matrix/matrix.hpp
- include/keisan/matrix/matrix.impl.hpp
- src/kalman.cpp
https://ichiro-its.atlassian.net/browse/PD-459
Describe problems, if any, clearly and concisely.
Describe any changes that have been made in this pull request.
- `feature/JIRA-ID-SHORT-DESCRIPTION` if has a JIRA ticket
- `enhancement/SHORT-DESCRIPTION` if has/has no JIRA ticket and contain enhancement
- `hotfix/SHORT-DESCRIPTION` if the change doesn't need to be tested (urgent)
> [Enhancement] Implement Kalman Filter
